# $FreeBSD$

PORTNAME=	xplain2sql
DISTVERSION= 5.0.1
CATEGORIES=	devel
MASTER_SITES=	http://www.berenddeboer.net/xplain2sql/
DISTFILES=$(DISTNAME)-csrc.tar.gz

MAINTAINER=	berend@pobox.com
COMMENT=	Convert Xplain to a variety of SQL dialects

LICENSE=	MIT

.include <bsd.port.mk>
