<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    version="1.0">

<!--

Example style sheet to generate an AppSync Apache Velocity Response template.

-->

<xsl:output
  method="text"
  version="1.0"
  encoding="UTF-8"/>


<xsl:param name="procedure-identifier"/>


<xsl:template match="/sql">
  <xsl:if test="$procedure-identifier = ''">
    <xsl:message terminate="yes">Parameter procedure-identifier is required.</xsl:message>
  </xsl:if>
  <xsl:if test="not(storedProcedure[@identifier = $procedure-identifier])">
    <xsl:message terminate="yes">No procedure with identifier <xsl:value-of select="@procedure-identifier"/> found.</xsl:message>
  </xsl:if>
  <xsl:apply-templates select="storedProcedure[@identifier = $procedure-identifier]"/>
</xsl:template>


<xsl:template match="storedProcedure">
<xsl:text/>## Generated by xplain2sql and appsync-response-vtl.xsl
#if($ctx.error)
  $utils.error($ctx.error.message, $ctx.error.type)
#end
$utils.toJson($utils.rds.toJsonObject($ctx.result)[0])
</xsl:template>


<xsl:template match="storedProcedure[not(select/column)]">
<xsl:text/>## Generated by xplain2sql and appsync-response-vtl.xsl
#if($ctx.error)
  $utils.error($ctx.error.message, $ctx.error.type)
#end
[]
</xsl:template>


</xsl:stylesheet>
